# Generated by Django 5.1.2 on 2024-10-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_colorvarient_sizevarient_product_color_varient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
